// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ek9eLgYUEIPsjT5a-ZqSVLuj3tKv6eE',
    appId: '1:499755655373:web:9cbd095452a8b793ae8984',
    messagingSenderId: '499755655373',
    projectId: 'saas-gym-37d51',
    authDomain: 'saas-gym-37d51.firebaseapp.com',
    storageBucket: 'saas-gym-37d51.firebasestorage.app',
    measurementId: 'G-BP1GN3FX6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZj9j2d7Aunf1f6fXc4Mj5x1SATxLES1M',
    appId: '1:499755655373:android:743b4cc0a68d6d80ae8984',
    messagingSenderId: '499755655373',
    projectId: 'saas-gym-37d51',
    storageBucket: 'saas-gym-37d51.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNSpN96-T4tljQCMcF9q62maT5HvNnpI',
    appId: '1:499755655373:ios:930d02b1590dcea2ae8984',
    messagingSenderId: '499755655373',
    projectId: 'saas-gym-37d51',
    storageBucket: 'saas-gym-37d51.firebasestorage.app',
    iosBundleId: 'id.gym.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNSpN96-T4tljQCMcF9q62maT5HvNnpI',
    appId: '1:499755655373:ios:421ee856c96469dfae8984',
    messagingSenderId: '499755655373',
    projectId: 'saas-gym-37d51',
    storageBucket: 'saas-gym-37d51.firebasestorage.app',
    iosBundleId: 'id.gym.mobile.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ek9eLgYUEIPsjT5a-ZqSVLuj3tKv6eE',
    appId: '1:499755655373:web:d097f96b107d2d40ae8984',
    messagingSenderId: '499755655373',
    projectId: 'saas-gym-37d51',
    authDomain: 'saas-gym-37d51.firebaseapp.com',
    storageBucket: 'saas-gym-37d51.firebasestorage.app',
    measurementId: 'G-GYZPB8FQG0',
  );
}
