import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

abstract final class AppLucideIcons {
  static const IconData activity = LucideIcons.activity;
  static const IconData badgeCheck = LucideIcons.badgeCheck;
  static const IconData badgeInfo = LucideIcons.badgeInfo;
  static const IconData bell = LucideIcons.bell;
  static const IconData bike = LucideIcons.bike;
  static const IconData building = LucideIcons.building2;
  static const IconData calendar = LucideIcons.calendarDays;
  static const IconData calendarCheck = LucideIcons.calendarCheck;
  static const IconData calendarClock = LucideIcons.calendarClock;
  static const IconData calendarPlus = LucideIcons.calendarPlus;
  static const IconData chart = LucideIcons.chartNoAxesColumnIncreasing;
  static const IconData check = LucideIcons.check;
  static const IconData chevronLeft = LucideIcons.chevronLeft;
  static const IconData chevronRight = LucideIcons.chevronRight;
  static const IconData circleCheck = LucideIcons.circleCheck;
  static const IconData clock = LucideIcons.clock;
  static const IconData door = LucideIcons.doorOpen;
  static const IconData drink = LucideIcons.glassWater;
  static const IconData dumbbell = LucideIcons.dumbbell;
  static const IconData eye = LucideIcons.eye;
  static const IconData eyeOff = LucideIcons.eyeOff;
  static const IconData flame = LucideIcons.flame;
  static const IconData heart = LucideIcons.heart;
  static const IconData history = LucideIcons.history;
  static const IconData home = LucideIcons.home;
  static const IconData info = LucideIcons.info;
  static const IconData leaf = LucideIcons.leaf;
  static const IconData lock = LucideIcons.lock;
  static const IconData logIn = LucideIcons.logIn;
  static const IconData logOut = LucideIcons.logOut;
  static const IconData mail = LucideIcons.mail;
  static const IconData map = LucideIcons.map;
  static const IconData mapPin = LucideIcons.mapPin;
  static const IconData mapPinned = LucideIcons.mapPinned;
  static const IconData music = LucideIcons.music;
  static const IconData navigation = LucideIcons.navigation;
  static const IconData parking = LucideIcons.parkingCircle;
  static const IconData person = LucideIcons.userRound;
  static const IconData phone = LucideIcons.phone;
  static const IconData qrCode = LucideIcons.qrCode;
  static const IconData qrScanner = LucideIcons.scanQrCode;
  static const IconData search = LucideIcons.search;
  static const IconData security = LucideIcons.shieldCheck;
  static const IconData share = LucideIcons.share2;
  static const IconData shower = LucideIcons.showerHead;
  static const IconData sparkles = LucideIcons.sparkles;
  static const IconData star = LucideIcons.star;
  static const IconData timer = LucideIcons.timer;
  static const IconData userPlus = LucideIcons.userPlus;
  static const IconData users = LucideIcons.users;
  static const IconData wifi = LucideIcons.wifi;
}
